name: Flutter

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2.11.0
      with:
        channel: 'stable'
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build apk --release
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "releases/*.apk"
        token: ${{ secrets.TOKEN }}
